### ISSUE TITLE
TICKET FEATURES

### ISSUE THREAD

**Issue by MrPotato374** [Nirlep5252/EpicBot#42]
add a "close" and "claim" button when someone opens a ticket. Close = Close a ticket | Claim = Maybe staff with a specific "support role" will be able to claim the ticket

add a way to open tickets channel instead of threads

**Comment by ShackerFox** [comment]
oh my bad, sorry Nirlep

**Comment by Nirlep5252** [comment]
its oke! np! ❤️

**Comment by MrPotato374** [comment]
that was fast
