### ISSUE TITLE
All My Suggestions

### ISSUE THREAD

**Issue by MrPotato374** [Nirlep5252/EpicBot#46]
Here all my suggestions :))

**Comment by MrPotato374** [comment]
automod nsfw? 
LIKE DELETE NSFW IMAGES WHEN THEY SEND 👀

**Comment by MrPotato374** [comment]
invite roles
- When a user reaches an amount of **real** invites, they get a role set by the staff members of their server (like leveling roles but for invites)

**Comment by Nirlep5252** [comment]
invite rewards are against the tos 
server admins can reward the roles manually if they want to

**Comment by MrPotato374** [comment]
o ok rip

**Comment by brixk** [comment]
YES.

**Comment by brixk** [comment]
:lenny:

**Comment by Nirlep5252** [comment]
Added to todo list: https://github.com/Nirlep5252/EpicBot/projects/2#card-67997868

🏃 will add soon

**Comment by MrPotato374** [comment]
improve the tic tac toe command
maybe change it to using buttons?

**Comment by ShackerFox** [comment]
yeah

**Comment by brixk** [comment]
> Added to todo list: https://github.com/Nirlep5252/EpicBot/projects/2#card-67997868
> 
> 🏃 will add soon

so thats just trello

**Comment by MrPotato374** [comment]
SERVER BACKUP COMMANDS

**Comment by Nirlep5252** [comment]
👌

**Comment by MrPotato374** [comment]
Stick Roles
So basically when the user leave the server and joined the server, they will receive their roles back

**Comment by Nirlep5252** [comment]
🤔

**Comment by ShackerFox** [comment]
@Nirlep5252 should I put all of my previous suggestions over here?

**Comment by Nirlep5252** [comment]
You should probably open a new issue for that
This would become really messy-

**Comment by ShackerFox** [comment]
@Nirlep5252 yeah I meant that

**Comment by JohnnyJTH** [comment]
@MrPotato374 @Nirlep5252 for the backups you can use this as a base, or inspiration...
https://github.com/Xenon-Bot/xenon

**Comment by Nirlep5252** [comment]
👀 Sure I'll look into it, thanks

**Comment by JohnnyJTH** [comment]
It's a very outdated version of the bot but it's really good. Have tried it myself too, and maybe it's a good thing it doesn't represent the current bot too much :wink:

**Comment by MrPotato374** [comment]
xenon good bot 👍

**Comment by brixk** [comment]
**xenon good bot**

**bottom text**

**Comment by MrPotato374** [comment]
Here's a suggestion from me which benefits nirlep and the contributers/kids/self hosters
Since the serverconfig.py files has like over 1k+ lines. I suggest you to move the code functions to other files
like:
```
async def change_starboard_channe(channel):
  #do stuff
```
then at the command do like:
```
@commands.command()
async def starboard_channel(self, ctx, channel: discord.TextChannel):
     await change_starboard_channel(channel)
```
yea something like that, just move the functions to another file and import them and just add into command so it wont takes a lot of lines in one file

**Comment by Nirlep5252** [comment]
Yee I was actually thinking of doing that, but what I'm gonna do is, I'm gonna move the configuration to their own cogs like all the starboards commands will be moved to its own cog, and selfroles to their own and so on... 

Because the config cog is just filled with stuff and users who use the bot don't even really notice all the good configuration features when they use the help command so that would be nice, I'll definitely do one of the 2 soon after implementing slash commands.

**Comment by MrPotato374** [comment]
ahh ok nice then

**Comment by MrPotato374** [comment]
but the help command will be full of different categories tho

**Comment by Nirlep5252** [comment]
I have an idea for it 😏 dw about it
I'll just remake the help command 3561897th time! 👍

**Comment by MrPotato374** [comment]
GG ok geniuslep

**Comment by brixk** [comment]
gg fluked it 32% - 100% 13 att cool level

**Comment by MrPotato374** [comment]
Suggestion: Add arguments to custom commands like: `e!test hi` then it will reply with `hi`

- Credits to the suggester: vivi aka cutepogamazingsmartsmortwonderfulgeniuspogincredibleepicepikvivi

**Comment by Nirlep5252** [comment]
sounds dope 👌
