### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by mrmaton** [Nirlep5252/EpicBot#51]
Hello, I have errors while installing requirements and launching...
![IMG_20210902_003529](https://user-images.githubusercontent.com/76999899/131755030-4411291c-1c45-4699-b398-8bf38c019e40.jpg)
![Uploading IMG_20210902_002139.jpg…]()
![Uploading IMG_20210902_003529.jpg…]()

**Comment by DeveloperJosh** [comment]
You could probably get a faster reply in the support server https://discord.gg/yQaj6Zmq

**Comment by Nirlep5252** [comment]
Try removing `disputils` from the requirements as that is no longer being used in the bot. It should fix your issue.

**Comment by mrmaton** [comment]
Fixed, thx so much

**Comment by Nirlep5252** [comment]
np!
