### ISSUE TITLE
Mute feature 

### ISSUE THREAD

**Issue by oxcakmak** [Nirlep5252/EpicBot#66]
I also want to add a description to the ban feature.

Without authorization, the reason for the ban should be stated.

**Comment by Nirlep5252** [comment]
The mute feature already exists, you can view it [here](https://github.com/Nirlep5252/EpicBot/blob/main/cogs/mod.py#L750-L812)

The ban reason also exists but it is just optional for the moderator, just like Discord's built in ban.
You can view the ban command code [here](https://github.com/Nirlep5252/EpicBot/blob/main/cogs/mod.py#L1011-L1059)

**Comment by oxcakmak** [comment]
Thank you very much and can I help you for Turkish language?

**Comment by Nirlep5252** [comment]
You mean adding Turkish translations in EpicBot? Sure! but currently EpicBot isn't multilingual.
I'm planning on making it multilingual when I start working on it again after 3 to 4 months (after my exams end)

I'll put up an announcement in the Discord server once it's ready to be translated :)

**Comment by oxcakmak** [comment]
Waiting Impatiently

**Comment by MrPotato374** [comment]
looking forward to it 👀
