### ISSUE TITLE
Restrict

### ISSUE THREAD

**Issue by oxcakmak** [Nirlep5252/EpicBot#67]
How to restrict everyone command using?
eg: music bot skip only dj role given

**Comment by Nirlep5252** [comment]
You cannot change the default command restrictions 🤔 
Like for the skip command, if a regular user tries to skip then it starts a vote for the song to be skipped
if half of the people in VC agree and vote, then the song is skipped

And if an admin tries to skip then it skips directly without voting

**Comment by Nirlep5252** [comment]
For restricting commands, Discord is already working on a built-in feature for changing permissions for slash commands from the settings itself, you can read more about it [here](https://msciotti.notion.site/msciotti/Command-Permissions-V2-4d113cb49090409f998f3bd80a06c3bd).

**Comment by oxcakmak** [comment]
By the way, I will do roleplaying with the button, but it works very slowly.

**Comment by Nirlep5252** [comment]
Wdym?
