### ISSUE TITLE
slash commands

### ISSUE THREAD

**Issue by ResetXD** [Nirlep5252/EpicBot#71]
application commands has started a new era of slash commands and interactions, Pycord supports a better way to manage slash commands.

i can help in development if you will be using Pycord, i am a verified python bot developer. reset#8278

i do recommend to convert to slash commands as traditional commands wont help if other's bot gets verified in 2022 and who always depends on PRs

thanks.

**Comment by Nirlep5252** [comment]
I will be converting all the traditional commands into application commands and switching to another library eventually.
But I am not currently working on EpicBot atm. Whenever I do, I will hit you up if you are interested.
