### ISSUE TITLE
how to properly format webhooks in .env?

### ISSUE THREAD

**Issue by 1t8** [Nirlep5252/EpicBot#73]
i have no idea how to properly format the webhooks in .env

**Comment by Nirlep5252** [comment]
You need a variable (eg. `startup_webhook`) whose value would be the token of the webhook
and you will have to put the ID of that webhook in the [`config.py`](https://github.com/Nirlep5252/EpicBot/blob/main/config.py#L65-L71) file.

**Comment by Nirlep5252** [comment]
Your `.env` file should look something like this: 
![image](https://user-images.githubusercontent.com/70529587/147025611-f3f39e16-df77-404f-9d0c-183ac821b834.png)

**Comment by 1t8** [comment]
do i have to write the entire webhook?
or just the token like you said
> whose value would be the token of the webhook

**Comment by Nirlep5252** [comment]
token

**Comment by 1t8** [comment]
got it working thank you for your cooperation
