### ISSUE TITLE
DANNY IS BACK (DPY)

### ISSUE THREAD

**Issue by MrPotato374** [Nirlep5252/EpicBot#79]
Recently Danny, the owner of DPY which is also known as Discord.py has returned into development including slash commands, new discord 'modals' and a bunch of stuff
More Info: https://gist.github.com/Rapptz/c4324f17a80c94776832430007ad40e6
DPY Repository: https://github.com/Rapptz/discord.py

Just saying here to inform Nirlep since he isn't on Discord very often idk if he already know this maybe he has 
**✨ MAGIK ✨**
Also NIRLEP WE MISS YOUUU 
COME BACK!

![image](https://user-images.githubusercontent.com/75535434/156921571-72fe42bd-c126-445c-b056-e2905f52fe01.png)

**Comment by DTS-11** [comment]
what happened to the server? is it deleted?

**Comment by MrPotato374** [comment]
yeah i think so :(
