### ISSUE TITLE
Here's a great idea

### ISSUE THREAD

**Issue by CyberDudeJ** [Nirlep5252/EpicBot#81]
Maybe, perchance, use commit messages which (and you'll cry when you read this) **make sense**.

**Comment by Nirlep5252** [comment]
I know. I was like that 2 years ago. Not everyone starts perfectly. In my newer projects I have improved and I am still trying to improve. If I ever come back to this project you'll see better commit messages.

**Comment by Motzumoto** [comment]
hope you come back soon nirlep :)
